/********************************************************************************
** Form generated from reading UI file 'nesca_3.ui'
**
** Created by: Qt User Interface Compiler version 5.15.17
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_NESCA_3_H
#define UI_NESCA_3_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_nesca_3Class
{
public:
    QWidget *centralWidget;
    QWidget *widget;
    QTabWidget *tabMainWidget;
    QWidget *tab_4;
    QPushButton *startScanButton_3;
    QLineEdit *ipLine;
    QLineEdit *ipmPortLine;
    QLineEdit *threadLine;
    QLabel *labelIPRange;
    QLabel *labelIPPorts;
    QLabel *labelIPThreads;
    QLabel *labelIPTO;
    QLineEdit *iptoLine_value;
    QPushButton *restoreDefaultPorts1;
    QWidget *tab_5;
    QLineEdit *dnsLine;
    QPushButton *startScanButton_4;
    QLineEdit *lineILVL;
    QLineEdit *dnsPortLine;
    QLineEdit *lineEditThread;
    QLabel *labelDNSRange;
    QLabel *labelDNSPorts;
    QLabel *labelDNSThreads;
    QLabel *labelIPTO_2;
    QLineEdit *iptoLine_value_2;
    QPushButton *restoreDefaultPorts2;
    QWidget *tab_6;
    QPushButton *importButton;
    QLabel *labelIpRange_9;
    QLineEdit *importThreads;
    QLineEdit *importPortLine;
    QLabel *labelDNSThreads_2;
    QLabel *labelDNSPorts_2;
    QLabel *labelIPTO_3;
    QLineEdit *iptoLine_value_3;
    QPushButton *restoreDefaultPorts3;
    QWidget *tab;
    QCheckBox *trackerOnOff;
    QLineEdit *lineTrackerScr;
    QLineEdit *lineTrackerSrv;
    QLineEdit *linePersKey;
    QLineEdit *trcSrvPortLine;
    QPushButton *checkKeyBut;
    QCheckBox *pingingOnOff;
    QLineEdit *PingTO;
    QLabel *label;
    QLineEdit *threadDelayBox;
    QLabel *label_2;
    QLabel *MaxBrutingThrLabel;
    QLineEdit *maxBrutingThrBox;
    QCheckBox *shuffle_onoff;
    QLineEdit *systemProxyIP;
    QLineEdit *systemProxyPort;
    QLabel *labelNesca_3;
    QFrame *line;
    QPushButton *exitButton;
    QLabel *labelThreads;
    QLabel *ipLabel;
    QLabel *labelRunningThreads;
    QTextBrowser *dataText;
    QLabel *labelTargetsLeft;
    QLabel *labelPendingTargets;
    QFrame *line_2;
    QGraphicsView *graphicLog;
    QLabel *RedLabel;
    QLabel *YellowLabel;
    QLabel *GreenLabel;
    QLabel *BlueLabel;
    QLabel *CyanLabel;
    QLabel *PinkLabel;
    QLabel *labelAnomaly;
    QLabel *labelBA;
    QLabel *labelFiltered;
    QLabel *labelBads;
    QLabel *labelOverloads;
    QLabel *labelLowloads;
    QPushButton *logoLabel;
    QLabel *WhiteLabel;
    QLabel *labelAlives;
    QGraphicsView *graphicLog_2;
    QPushButton *me2ScanBut;
    QPushButton *QoSScanBut;
    QGraphicsView *graphicDelim;
    QGraphicsView *graphicLog_Upper;
    QPushButton *switcherBut;
    QGraphicsView *graphicActivityGrid;
    QGraphicsView *graphicActivity;
    QGraphicsView *graphicTextPlacer;
    QPushButton *VoiceScanBut;
    QGraphicsView *graphicsVoice;
    QPushButton *clearLogBut;
    QPushButton *secretMessageBut_1;
    QPushButton *secretMessageBut_2;
    QPushButton *secretMessageBut_3;
    QPushButton *secretMessageBut_4;
    QPushButton *secretMessageBut_5;
    QPushButton *secretMessageBut_6;
    QPushButton *secretMessageBut_7;
    QPushButton *secretMessageBut_8;
    QLabel *newMessageLabel;
    QPushButton *PieStatBut;
    QPushButton *trayButton;
    QLabel *DredLabel;
    QLabel *labelSSH;
    QLabel *rVerLabel;
    QLabel *NSTrackStatusLabel;
    QGraphicsView *graphicsTest;
    QLabel *labelSavedValue;
    QLabel *labelSaved;
    QLineEdit *currentDirectoryLine;
    QTableView *BATableView;
    QWidget *widgetJOB;
    QGraphicsView *jobRangeVisual;
    QTableWidget *jobIPContractsTable;
    QTableWidget *jobIPWantedTable;
    QPushButton *DataflowModeBut;
    QPushButton *JobModeBut;
    QPushButton *edit_filter_button;

    void setupUi(QMainWindow *nesca_3Class)
    {
        if (nesca_3Class->objectName().isEmpty())
            nesca_3Class->setObjectName(QString::fromUtf8("nesca_3Class"));
        nesca_3Class->resize(500, 800);
        nesca_3Class->setMinimumSize(QSize(500, 400));
        nesca_3Class->setMaximumSize(QSize(500, 800));
        nesca_3Class->setMouseTracking(true);
        nesca_3Class->setAcceptDrops(true);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/nesca_3/Z:/nesca.ico"), QSize(), QIcon::Normal, QIcon::Off);
        nesca_3Class->setWindowIcon(icon);
        nesca_3Class->setWindowOpacity(1.000000000000000);
#if QT_CONFIG(tooltip)
        nesca_3Class->setToolTip(QString::fromUtf8(""));
#endif // QT_CONFIG(tooltip)
        nesca_3Class->setStyleSheet(QString::fromUtf8("background-color: rgba(49, 49, 49,0);"));
        nesca_3Class->setWindowFilePath(QString::fromUtf8(""));
        centralWidget = new QWidget(nesca_3Class);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        widget = new QWidget(centralWidget);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setGeometry(QRect(0, 0, 500, 800));
        QFont font;
        font.setFamily(QString::fromUtf8("Small Fonts"));
        font.setPointSize(7);
        widget->setFont(font);
        widget->setFocusPolicy(Qt::NoFocus);
        widget->setStyleSheet(QString::fromUtf8("background-color:qlineargradient(spread:pad, x1:0.541, y1:0.500364, x2:0.54, y2:0, stop:0 rgba(16, 16, 16, 255), stop:1 rgba(0, 0, 0, 255));"));
        tabMainWidget = new QTabWidget(widget);
        tabMainWidget->setObjectName(QString::fromUtf8("tabMainWidget"));
        tabMainWidget->setEnabled(true);
        tabMainWidget->setGeometry(QRect(10, 50, 481, 161));
        tabMainWidget->setFont(font);
        tabMainWidget->setStyleSheet(QString::fromUtf8("border: 0.4px solid #818181;background-color: rgba(2, 2, 2, 0);"));
        tabMainWidget->setTabPosition(QTabWidget::North);
        tabMainWidget->setTabShape(QTabWidget::Rounded);
        tabMainWidget->setElideMode(Qt::ElideMiddle);
        tabMainWidget->setUsesScrollButtons(false);
        tabMainWidget->setDocumentMode(true);
        tabMainWidget->setTabsClosable(false);
        tabMainWidget->setMovable(false);
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        tab_4->setEnabled(false);
        startScanButton_3 = new QPushButton(tab_4);
        startScanButton_3->setObjectName(QString::fromUtf8("startScanButton_3"));
        startScanButton_3->setGeometry(QRect(190, 110, 75, 23));
        startScanButton_3->setFont(font);
        startScanButton_3->setStyleSheet(QString::fromUtf8(""));
        ipLine = new QLineEdit(tab_4);
        ipLine->setObjectName(QString::fromUtf8("ipLine"));
        ipLine->setGeometry(QRect(110, 20, 221, 20));
        ipLine->setFont(font);
        ipLine->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        ipLine->setMaxLength(31);
        ipLine->setAlignment(Qt::AlignCenter);
        ipmPortLine = new QLineEdit(tab_4);
        ipmPortLine->setObjectName(QString::fromUtf8("ipmPortLine"));
        ipmPortLine->setGeometry(QRect(110, 50, 221, 20));
        ipmPortLine->setFont(font);
        ipmPortLine->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        ipmPortLine->setMaxLength(4096);
        threadLine = new QLineEdit(tab_4);
        threadLine->setObjectName(QString::fromUtf8("threadLine"));
        threadLine->setGeometry(QRect(110, 80, 51, 20));
        threadLine->setFont(font);
        threadLine->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        threadLine->setMaxLength(4);
        threadLine->setAlignment(Qt::AlignCenter);
        labelIPRange = new QLabel(tab_4);
        labelIPRange->setObjectName(QString::fromUtf8("labelIPRange"));
        labelIPRange->setGeometry(QRect(40, 20, 61, 20));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Small Fonts"));
        font1.setPointSize(7);
        font1.setBold(false);
        font1.setItalic(false);
        font1.setWeight(50);
        font1.setKerning(false);
        labelIPRange->setFont(font1);
        labelIPRange->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelIPPorts = new QLabel(tab_4);
        labelIPPorts->setObjectName(QString::fromUtf8("labelIPPorts"));
        labelIPPorts->setGeometry(QRect(54, 50, 34, 20));
        labelIPPorts->setFont(font1);
        labelIPPorts->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelIPThreads = new QLabel(tab_4);
        labelIPThreads->setObjectName(QString::fromUtf8("labelIPThreads"));
        labelIPThreads->setGeometry(QRect(40, 80, 61, 20));
        labelIPThreads->setFont(font1);
        labelIPThreads->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelIPTO = new QLabel(tab_4);
        labelIPTO->setObjectName(QString::fromUtf8("labelIPTO"));
        labelIPTO->setGeometry(QRect(220, 80, 46, 20));
        labelIPTO->setFont(font1);
        labelIPTO->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        iptoLine_value = new QLineEdit(tab_4);
        iptoLine_value->setObjectName(QString::fromUtf8("iptoLine_value"));
        iptoLine_value->setGeometry(QRect(280, 80, 51, 20));
        iptoLine_value->setFont(font);
        iptoLine_value->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        iptoLine_value->setMaxLength(4);
        iptoLine_value->setAlignment(Qt::AlignCenter);
        restoreDefaultPorts1 = new QPushButton(tab_4);
        restoreDefaultPorts1->setObjectName(QString::fromUtf8("restoreDefaultPorts1"));
        restoreDefaultPorts1->setGeometry(QRect(337, 52, 67, 16));
        restoreDefaultPorts1->setFont(font);
        restoreDefaultPorts1->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(255, 255, 255, 40);"));
        tabMainWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        tab_5->setEnabled(false);
        dnsLine = new QLineEdit(tab_5);
        dnsLine->setObjectName(QString::fromUtf8("dnsLine"));
        dnsLine->setGeometry(QRect(110, 20, 221, 20));
        dnsLine->setFont(font);
        dnsLine->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);"));
        dnsLine->setMaxLength(128);
        dnsLine->setAlignment(Qt::AlignCenter);
        startScanButton_4 = new QPushButton(tab_5);
        startScanButton_4->setObjectName(QString::fromUtf8("startScanButton_4"));
        startScanButton_4->setGeometry(QRect(190, 110, 75, 23));
        startScanButton_4->setFont(font);
        startScanButton_4->setStyleSheet(QString::fromUtf8(""));
        lineILVL = new QLineEdit(tab_5);
        lineILVL->setObjectName(QString::fromUtf8("lineILVL"));
        lineILVL->setGeometry(QRect(340, 20, 71, 20));
        lineILVL->setFont(font);
        lineILVL->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);"));
        lineILVL->setMaxLength(128);
        lineILVL->setAlignment(Qt::AlignCenter);
        dnsPortLine = new QLineEdit(tab_5);
        dnsPortLine->setObjectName(QString::fromUtf8("dnsPortLine"));
        dnsPortLine->setGeometry(QRect(110, 50, 221, 20));
        dnsPortLine->setFont(font);
        dnsPortLine->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);"));
        dnsPortLine->setMaxLength(4096);
        lineEditThread = new QLineEdit(tab_5);
        lineEditThread->setObjectName(QString::fromUtf8("lineEditThread"));
        lineEditThread->setGeometry(QRect(110, 80, 51, 20));
        lineEditThread->setFont(font);
        lineEditThread->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);"));
        lineEditThread->setMaxLength(4);
        lineEditThread->setAlignment(Qt::AlignCenter);
        labelDNSRange = new QLabel(tab_5);
        labelDNSRange->setObjectName(QString::fromUtf8("labelDNSRange"));
        labelDNSRange->setGeometry(QRect(30, 20, 61, 20));
        labelDNSRange->setFont(font1);
        labelDNSRange->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelDNSPorts = new QLabel(tab_5);
        labelDNSPorts->setObjectName(QString::fromUtf8("labelDNSPorts"));
        labelDNSPorts->setGeometry(QRect(54, 50, 34, 20));
        labelDNSPorts->setFont(font1);
        labelDNSPorts->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelDNSThreads = new QLabel(tab_5);
        labelDNSThreads->setObjectName(QString::fromUtf8("labelDNSThreads"));
        labelDNSThreads->setGeometry(QRect(40, 80, 61, 20));
        labelDNSThreads->setFont(font1);
        labelDNSThreads->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelIPTO_2 = new QLabel(tab_5);
        labelIPTO_2->setObjectName(QString::fromUtf8("labelIPTO_2"));
        labelIPTO_2->setGeometry(QRect(220, 80, 46, 20));
        labelIPTO_2->setFont(font1);
        labelIPTO_2->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        iptoLine_value_2 = new QLineEdit(tab_5);
        iptoLine_value_2->setObjectName(QString::fromUtf8("iptoLine_value_2"));
        iptoLine_value_2->setGeometry(QRect(280, 80, 51, 20));
        iptoLine_value_2->setFont(font);
        iptoLine_value_2->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        iptoLine_value_2->setMaxLength(4);
        iptoLine_value_2->setAlignment(Qt::AlignCenter);
        restoreDefaultPorts2 = new QPushButton(tab_5);
        restoreDefaultPorts2->setObjectName(QString::fromUtf8("restoreDefaultPorts2"));
        restoreDefaultPorts2->setGeometry(QRect(337, 52, 67, 16));
        restoreDefaultPorts2->setFont(font);
        restoreDefaultPorts2->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(255, 255, 255, 40);"));
        tabMainWidget->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        tab_6->setEnabled(false);
        importButton = new QPushButton(tab_6);
        importButton->setObjectName(QString::fromUtf8("importButton"));
        importButton->setGeometry(QRect(190, 110, 75, 23));
        importButton->setFont(font);
        importButton->setStyleSheet(QString::fromUtf8(""));
        labelIpRange_9 = new QLabel(tab_6);
        labelIpRange_9->setObjectName(QString::fromUtf8("labelIpRange_9"));
        labelIpRange_9->setGeometry(QRect(110, 0, 253, 37));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Eurostile"));
        font2.setPointSize(8);
        font2.setBold(false);
        font2.setItalic(false);
        font2.setWeight(50);
        font2.setKerning(false);
        labelIpRange_9->setFont(font2);
        labelIpRange_9->setStyleSheet(QString::fromUtf8("background-color: rgba(2, 2, 2, 0);\n"
"color: rgb(214, 214, 0);"));
        importThreads = new QLineEdit(tab_6);
        importThreads->setObjectName(QString::fromUtf8("importThreads"));
        importThreads->setGeometry(QRect(110, 80, 51, 20));
        importThreads->setFont(font);
        importThreads->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);"));
        importThreads->setMaxLength(4);
        importThreads->setAlignment(Qt::AlignCenter);
        importPortLine = new QLineEdit(tab_6);
        importPortLine->setObjectName(QString::fromUtf8("importPortLine"));
        importPortLine->setGeometry(QRect(110, 50, 221, 20));
        importPortLine->setFont(font);
        importPortLine->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);"));
        labelDNSThreads_2 = new QLabel(tab_6);
        labelDNSThreads_2->setObjectName(QString::fromUtf8("labelDNSThreads_2"));
        labelDNSThreads_2->setGeometry(QRect(40, 80, 61, 20));
        labelDNSThreads_2->setFont(font1);
        labelDNSThreads_2->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelDNSPorts_2 = new QLabel(tab_6);
        labelDNSPorts_2->setObjectName(QString::fromUtf8("labelDNSPorts_2"));
        labelDNSPorts_2->setGeometry(QRect(54, 50, 33, 20));
        labelDNSPorts_2->setFont(font1);
        labelDNSPorts_2->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelIPTO_3 = new QLabel(tab_6);
        labelIPTO_3->setObjectName(QString::fromUtf8("labelIPTO_3"));
        labelIPTO_3->setGeometry(QRect(220, 80, 46, 20));
        labelIPTO_3->setFont(font1);
        labelIPTO_3->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        iptoLine_value_3 = new QLineEdit(tab_6);
        iptoLine_value_3->setObjectName(QString::fromUtf8("iptoLine_value_3"));
        iptoLine_value_3->setGeometry(QRect(280, 80, 51, 20));
        iptoLine_value_3->setFont(font);
        iptoLine_value_3->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        iptoLine_value_3->setMaxLength(4);
        iptoLine_value_3->setAlignment(Qt::AlignCenter);
        restoreDefaultPorts3 = new QPushButton(tab_6);
        restoreDefaultPorts3->setObjectName(QString::fromUtf8("restoreDefaultPorts3"));
        restoreDefaultPorts3->setGeometry(QRect(337, 52, 67, 16));
        restoreDefaultPorts3->setFont(font);
        restoreDefaultPorts3->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(255, 255, 255, 40);"));
        tabMainWidget->addTab(tab_6, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        trackerOnOff = new QCheckBox(tab);
        trackerOnOff->setObjectName(QString::fromUtf8("trackerOnOff"));
        trackerOnOff->setGeometry(QRect(30, 120, 281, 17));
        trackerOnOff->setFont(font);
        trackerOnOff->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216); background-color: rgba(2, 2, 2, 0);"));
        trackerOnOff->setChecked(false);
        lineTrackerScr = new QLineEdit(tab);
        lineTrackerScr->setObjectName(QString::fromUtf8("lineTrackerScr"));
        lineTrackerScr->setGeometry(QRect(250, 2, 121, 16));
        lineTrackerScr->setFont(font);
        lineTrackerScr->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        lineTrackerScr->setMaxLength(256);
        lineTrackerScr->setAlignment(Qt::AlignCenter);
        lineTrackerSrv = new QLineEdit(tab);
        lineTrackerSrv->setObjectName(QString::fromUtf8("lineTrackerSrv"));
        lineTrackerSrv->setGeometry(QRect(30, 2, 211, 16));
        lineTrackerSrv->setFont(font);
        lineTrackerSrv->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        lineTrackerSrv->setMaxLength(256);
        lineTrackerSrv->setAlignment(Qt::AlignCenter);
        linePersKey = new QLineEdit(tab);
        linePersKey->setObjectName(QString::fromUtf8("linePersKey"));
        linePersKey->setGeometry(QRect(30, 22, 341, 12));
        linePersKey->setFont(font);
        linePersKey->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56); border:none;"));
        linePersKey->setMaxLength(32);
        linePersKey->setAlignment(Qt::AlignCenter);
        trcSrvPortLine = new QLineEdit(tab);
        trcSrvPortLine->setObjectName(QString::fromUtf8("trcSrvPortLine"));
        trcSrvPortLine->setGeometry(QRect(379, 2, 62, 16));
        trcSrvPortLine->setFont(font);
        trcSrvPortLine->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        trcSrvPortLine->setMaxLength(5);
        trcSrvPortLine->setAlignment(Qt::AlignCenter);
        checkKeyBut = new QPushButton(tab);
        checkKeyBut->setObjectName(QString::fromUtf8("checkKeyBut"));
        checkKeyBut->setGeometry(QRect(379, 18, 61, 16));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Eurostile"));
        font3.setPointSize(8);
        checkKeyBut->setFont(font3);
        checkKeyBut->setStyleSheet(QString::fromUtf8(""));
        pingingOnOff = new QCheckBox(tab);
        pingingOnOff->setObjectName(QString::fromUtf8("pingingOnOff"));
        pingingOnOff->setGeometry(QRect(30, 84, 75, 17));
        pingingOnOff->setFont(font);
        pingingOnOff->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216); background-color: rgba(2, 2, 2, 0);"));
        pingingOnOff->setChecked(false);
        PingTO = new QLineEdit(tab);
        PingTO->setObjectName(QString::fromUtf8("PingTO"));
        PingTO->setEnabled(false);
        PingTO->setGeometry(QRect(108, 86, 51, 15));
        PingTO->setFont(font);
        PingTO->setStyleSheet(QString::fromUtf8("color: rgb(116, 116, 116);background-color: rgb(56, 56, 56);border:none;"));
        PingTO->setMaxLength(5);
        PingTO->setAlignment(Qt::AlignCenter);
        label = new QLabel(tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(163, 85, 31, 16));
        label->setFont(font);
        label->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216); background-color: rgba(2, 2, 2, 0);"));
        threadDelayBox = new QLineEdit(tab);
        threadDelayBox->setObjectName(QString::fromUtf8("threadDelayBox"));
        threadDelayBox->setEnabled(true);
        threadDelayBox->setGeometry(QRect(390, 69, 51, 20));
        threadDelayBox->setFont(font);
        threadDelayBox->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        threadDelayBox->setMaxLength(5);
        threadDelayBox->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(tab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(320, 69, 68, 16));
        label_2->setFont(font);
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216); background-color: rgba(2, 2, 2, 0);"));
        MaxBrutingThrLabel = new QLabel(tab);
        MaxBrutingThrLabel->setObjectName(QString::fromUtf8("MaxBrutingThrLabel"));
        MaxBrutingThrLabel->setGeometry(QRect(320, 84, 62, 26));
        MaxBrutingThrLabel->setFont(font);
        MaxBrutingThrLabel->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216); background-color: rgba(2, 2, 2, 0);"));
        maxBrutingThrBox = new QLineEdit(tab);
        maxBrutingThrBox->setObjectName(QString::fromUtf8("maxBrutingThrBox"));
        maxBrutingThrBox->setEnabled(true);
        maxBrutingThrBox->setGeometry(QRect(390, 90, 51, 20));
        maxBrutingThrBox->setFont(font);
        maxBrutingThrBox->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        maxBrutingThrBox->setMaxLength(5);
        maxBrutingThrBox->setAlignment(Qt::AlignCenter);
        shuffle_onoff = new QCheckBox(tab);
        shuffle_onoff->setObjectName(QString::fromUtf8("shuffle_onoff"));
        shuffle_onoff->setGeometry(QRect(30, 68, 161, 17));
        shuffle_onoff->setFont(font);
        shuffle_onoff->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216); background-color: rgba(2, 2, 2, 0);"));
        shuffle_onoff->setChecked(true);
        systemProxyIP = new QLineEdit(tab);
        systemProxyIP->setObjectName(QString::fromUtf8("systemProxyIP"));
        systemProxyIP->setGeometry(QRect(30, 38, 341, 12));
        systemProxyIP->setFont(font);
        systemProxyIP->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56); border:none;"));
        systemProxyIP->setMaxLength(32);
        systemProxyIP->setAlignment(Qt::AlignCenter);
        systemProxyPort = new QLineEdit(tab);
        systemProxyPort->setObjectName(QString::fromUtf8("systemProxyPort"));
        systemProxyPort->setGeometry(QRect(379, 38, 62, 12));
        systemProxyPort->setFont(font);
        systemProxyPort->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgb(56, 56, 56);border:none;"));
        systemProxyPort->setMaxLength(5);
        systemProxyPort->setAlignment(Qt::AlignCenter);
        tabMainWidget->addTab(tab, QString());
        labelNesca_3 = new QLabel(widget);
        labelNesca_3->setObjectName(QString::fromUtf8("labelNesca_3"));
        labelNesca_3->setGeometry(QRect(123, 11, 271, 20));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Verdana"));
        font4.setPointSize(8);
        font4.setBold(true);
        font4.setUnderline(false);
        font4.setWeight(75);
        labelNesca_3->setFont(font4);
        labelNesca_3->setMouseTracking(true);
        labelNesca_3->setAcceptDrops(true);
        labelNesca_3->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelNesca_3->setTextFormat(Qt::PlainText);
        labelNesca_3->setAlignment(Qt::AlignCenter);
        labelNesca_3->setOpenExternalLinks(true);
        line = new QFrame(widget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setWindowModality(Qt::NonModal);
        line->setGeometry(QRect(10, 30, 480, 16));
        line->setFont(font);
        line->setAutoFillBackground(false);
        line->setStyleSheet(QString::fromUtf8("color: white;background-color: rgba(2, 2, 2, 0);"));
        line->setFrameShadow(QFrame::Plain);
        line->setFrameShape(QFrame::HLine);
        exitButton = new QPushButton(widget);
        exitButton->setObjectName(QString::fromUtf8("exitButton"));
        exitButton->setGeometry(QRect(470, 10, 10, 20));
        exitButton->setFont(font);
        exitButton->setStyleSheet(QString::fromUtf8("background-color: rgba(0, 0, 0, 0);"));
        labelThreads = new QLabel(widget);
        labelThreads->setObjectName(QString::fromUtf8("labelThreads"));
        labelThreads->setGeometry(QRect(89, 325, 15, 15));
        QFont font5;
        font5.setFamily(QString::fromUtf8("MS Sans Serif"));
        font5.setPointSize(10);
        font5.setBold(false);
        font5.setUnderline(false);
        font5.setWeight(50);
        font5.setKerning(false);
        labelThreads->setFont(font5);
        labelThreads->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        ipLabel = new QLabel(widget);
        ipLabel->setObjectName(QString::fromUtf8("ipLabel"));
        ipLabel->setGeometry(QRect(37, 351, 150, 20));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(ipLabel->sizePolicy().hasHeightForWidth());
        ipLabel->setSizePolicy(sizePolicy);
        QFont font6;
        font6.setFamily(QString::fromUtf8("Small Fonts"));
        font6.setPointSize(7);
        font6.setBold(false);
        font6.setUnderline(true);
        font6.setWeight(50);
        ipLabel->setFont(font6);
        ipLabel->setAutoFillBackground(false);
        ipLabel->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        ipLabel->setAlignment(Qt::AlignCenter);
        labelRunningThreads = new QLabel(widget);
        labelRunningThreads->setObjectName(QString::fromUtf8("labelRunningThreads"));
        labelRunningThreads->setGeometry(QRect(105, 324, 67, 20));
        QFont font7;
        font7.setFamily(QString::fromUtf8("Small Fonts"));
        font7.setPointSize(7);
        font7.setBold(false);
        font7.setUnderline(false);
        font7.setWeight(50);
        labelRunningThreads->setFont(font7);
        labelRunningThreads->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216); background-color: rgba(2, 2, 2, 0);"));
        dataText = new QTextBrowser(widget);
        dataText->setObjectName(QString::fromUtf8("dataText"));
        dataText->setEnabled(true);
        dataText->setGeometry(QRect(20, 445, 453, 326));
        dataText->setFont(font7);
        dataText->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 26,26); border: 1px solid white;"));
        dataText->setLocale(QLocale(QLocale::Japanese, QLocale::Japan));
        dataText->setFrameShape(QFrame::NoFrame);
        dataText->setFrameShadow(QFrame::Plain);
        dataText->setSizeAdjustPolicy(QAbstractScrollArea::AdjustIgnored);
        dataText->setUndoRedoEnabled(false);
        dataText->setLineWrapMode(QTextEdit::NoWrap);
        dataText->setReadOnly(true);
        dataText->setCursorWidth(5);
        dataText->setTextInteractionFlags(Qt::TextBrowserInteraction);
        dataText->setOpenExternalLinks(true);
        dataText->setOpenLinks(false);
        labelTargetsLeft = new QLabel(widget);
        labelTargetsLeft->setObjectName(QString::fromUtf8("labelTargetsLeft"));
        labelTargetsLeft->setGeometry(QRect(90, 338, 16, 15));
        QFont font8;
        font8.setFamily(QString::fromUtf8("MS Sans Serif"));
        font8.setPointSize(10);
        font8.setBold(false);
        font8.setItalic(false);
        font8.setUnderline(false);
        font8.setWeight(50);
        labelTargetsLeft->setFont(font8);
        labelTargetsLeft->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelPendingTargets = new QLabel(widget);
        labelPendingTargets->setObjectName(QString::fromUtf8("labelPendingTargets"));
        labelPendingTargets->setGeometry(QRect(105, 337, 71, 20));
        labelPendingTargets->setFont(font7);
        labelPendingTargets->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        line_2 = new QFrame(widget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setWindowModality(Qt::NonModal);
        line_2->setGeometry(QRect(10, 210, 480, 16));
        line_2->setFont(font);
        line_2->setAutoFillBackground(false);
        line_2->setStyleSheet(QString::fromUtf8("color: white;background-color: rgba(2, 2, 2, 0);"));
        line_2->setFrameShadow(QFrame::Plain);
        line_2->setFrameShape(QFrame::HLine);
        graphicLog = new QGraphicsView(widget);
        graphicLog->setObjectName(QString::fromUtf8("graphicLog"));
        graphicLog->setGeometry(QRect(220, 265, 270, 100));
        graphicLog->setFont(font);
        graphicLog->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 26,26); border: 1px solid white;"));
        graphicLog->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicLog->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        RedLabel = new QLabel(widget);
        RedLabel->setObjectName(QString::fromUtf8("RedLabel"));
        RedLabel->setEnabled(true);
        RedLabel->setGeometry(QRect(235, 370, 8, 5));
        RedLabel->setFont(font);
        RedLabel->setStyleSheet(QString::fromUtf8("background-color: red; visible: false;"));
        YellowLabel = new QLabel(widget);
        YellowLabel->setObjectName(QString::fromUtf8("YellowLabel"));
        YellowLabel->setGeometry(QRect(235, 400, 8, 5));
        YellowLabel->setFont(font);
        YellowLabel->setStyleSheet(QString::fromUtf8("background-color: #52b4e5;"));
        GreenLabel = new QLabel(widget);
        GreenLabel->setObjectName(QString::fromUtf8("GreenLabel"));
        GreenLabel->setGeometry(QRect(370, 370, 8, 5));
        GreenLabel->setFont(font);
        GreenLabel->setStyleSheet(QString::fromUtf8("background-color: green;"));
        BlueLabel = new QLabel(widget);
        BlueLabel->setObjectName(QString::fromUtf8("BlueLabel"));
        BlueLabel->setGeometry(QRect(235, 385, 8, 5));
        BlueLabel->setFont(font);
        BlueLabel->setStyleSheet(QString::fromUtf8("background-color: blue;"));
        CyanLabel = new QLabel(widget);
        CyanLabel->setObjectName(QString::fromUtf8("CyanLabel"));
        CyanLabel->setGeometry(QRect(370, 385, 8, 5));
        CyanLabel->setFont(font);
        CyanLabel->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 85, 0);"));
        PinkLabel = new QLabel(widget);
        PinkLabel->setObjectName(QString::fromUtf8("PinkLabel"));
        PinkLabel->setGeometry(QRect(370, 400, 8, 5));
        PinkLabel->setFont(font);
        PinkLabel->setStyleSheet(QString::fromUtf8("background-color: violet;"));
        labelAnomaly = new QLabel(widget);
        labelAnomaly->setObjectName(QString::fromUtf8("labelAnomaly"));
        labelAnomaly->setGeometry(QRect(250, 368, 91, 8));
        labelAnomaly->setFont(font1);
        labelAnomaly->setLayoutDirection(Qt::RightToLeft);
        labelAnomaly->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelAnomaly->setTextFormat(Qt::AutoText);
        labelAnomaly->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        labelBA = new QLabel(widget);
        labelBA->setObjectName(QString::fromUtf8("labelBA"));
        labelBA->setGeometry(QRect(250, 383, 61, 8));
        labelBA->setFont(font1);
        labelBA->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelFiltered = new QLabel(widget);
        labelFiltered->setObjectName(QString::fromUtf8("labelFiltered"));
        labelFiltered->setGeometry(QRect(385, 383, 51, 8));
        labelFiltered->setFont(font1);
        labelFiltered->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelBads = new QLabel(widget);
        labelBads->setObjectName(QString::fromUtf8("labelBads"));
        labelBads->setGeometry(QRect(385, 368, 91, 8));
        labelBads->setFont(font1);
        labelBads->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelOverloads = new QLabel(widget);
        labelOverloads->setObjectName(QString::fromUtf8("labelOverloads"));
        labelOverloads->setGeometry(QRect(250, 398, 51, 8));
        labelOverloads->setFont(font1);
        labelOverloads->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        labelLowloads = new QLabel(widget);
        labelLowloads->setObjectName(QString::fromUtf8("labelLowloads"));
        labelLowloads->setGeometry(QRect(385, 398, 61, 8));
        labelLowloads->setFont(font1);
        labelLowloads->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        logoLabel = new QPushButton(widget);
        logoLabel->setObjectName(QString::fromUtf8("logoLabel"));
        logoLabel->setGeometry(QRect(11, 10, 21, 20));
        logoLabel->setFont(font);
        logoLabel->setStyleSheet(QString::fromUtf8("border:none; background-color:black;"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/nesca_3/nesca.ico"), QSize(), QIcon::Normal, QIcon::Off);
        logoLabel->setIcon(icon1);
        WhiteLabel = new QLabel(widget);
        WhiteLabel->setObjectName(QString::fromUtf8("WhiteLabel"));
        WhiteLabel->setGeometry(QRect(370, 415, 8, 5));
        WhiteLabel->setFont(font);
        WhiteLabel->setStyleSheet(QString::fromUtf8("background-color: white;"));
        labelAlives = new QLabel(widget);
        labelAlives->setObjectName(QString::fromUtf8("labelAlives"));
        labelAlives->setGeometry(QRect(385, 413, 61, 8));
        labelAlives->setFont(font1);
        labelAlives->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        graphicLog_2 = new QGraphicsView(widget);
        graphicLog_2->setObjectName(QString::fromUtf8("graphicLog_2"));
        graphicLog_2->setGeometry(QRect(220, 265, 270, 100));
        graphicLog_2->setFont(font);
        graphicLog_2->setStyleSheet(QString::fromUtf8("border:none;background-color: rgba(26, 26,26, 0);"));
        graphicLog_2->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicLog_2->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicLog_2->setRenderHints(QPainter::HighQualityAntialiasing|QPainter::TextAntialiasing);
        graphicLog_2->setCacheMode(QGraphicsView::CacheNone);
        me2ScanBut = new QPushButton(widget);
        me2ScanBut->setObjectName(QString::fromUtf8("me2ScanBut"));
        me2ScanBut->setGeometry(QRect(220, 253, 60, 10));
        me2ScanBut->setFont(font);
        me2ScanBut->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(255, 255, 255, 40);"));
        QoSScanBut = new QPushButton(widget);
        QoSScanBut->setObjectName(QString::fromUtf8("QoSScanBut"));
        QoSScanBut->setGeometry(QRect(281, 253, 60, 10));
        QoSScanBut->setFont(font);
        QoSScanBut->setStyleSheet(QString::fromUtf8("color: rgb(130, 130, 130);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(130, 130, 130, 80);"));
        graphicDelim = new QGraphicsView(widget);
        graphicDelim->setObjectName(QString::fromUtf8("graphicDelim"));
        graphicDelim->setGeometry(QRect(220, 265, 270, 100));
        graphicDelim->setFont(font);
        graphicDelim->setStyleSheet(QString::fromUtf8("border:none;background-color: rgba(26, 26,26, 0);"));
        graphicDelim->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicDelim->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicLog_Upper = new QGraphicsView(widget);
        graphicLog_Upper->setObjectName(QString::fromUtf8("graphicLog_Upper"));
        graphicLog_Upper->setGeometry(QRect(220, 265, 270, 100));
        graphicLog_Upper->setFont(font);
        graphicLog_Upper->setStyleSheet(QString::fromUtf8("border:none;background-color: rgba(26, 26,26, 0);"));
        graphicLog_Upper->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicLog_Upper->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicLog_Upper->setRenderHints(QPainter::TextAntialiasing);
        graphicLog_Upper->setCacheMode(QGraphicsView::CacheNone);
        switcherBut = new QPushButton(widget);
        switcherBut->setObjectName(QString::fromUtf8("switcherBut"));
        switcherBut->setGeometry(QRect(475, 467, 16, 21));
        switcherBut->setFont(font);
        switcherBut->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(255, 255, 255, 40);"));
        graphicActivityGrid = new QGraphicsView(widget);
        graphicActivityGrid->setObjectName(QString::fromUtf8("graphicActivityGrid"));
        graphicActivityGrid->setGeometry(QRect(373, 780, 100, 16));
        graphicActivityGrid->setFont(font);
        graphicActivityGrid->setStyleSheet(QString::fromUtf8("border:1px solid white;background-color: rgba(26, 26,26, 0);"));
        graphicActivityGrid->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicActivityGrid->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicActivityGrid->setRenderHints(QPainter::Antialiasing|QPainter::HighQualityAntialiasing|QPainter::TextAntialiasing);
        graphicActivityGrid->setCacheMode(QGraphicsView::CacheNone);
        graphicActivity = new QGraphicsView(widget);
        graphicActivity->setObjectName(QString::fromUtf8("graphicActivity"));
        graphicActivity->setGeometry(QRect(373, 780, 100, 16));
        graphicActivity->setFont(font);
        graphicActivity->setStyleSheet(QString::fromUtf8("border:none;background-color: rgba(26, 26,26, 0);"));
        graphicActivity->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicActivity->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicActivity->setRenderHints(QPainter::Antialiasing|QPainter::HighQualityAntialiasing|QPainter::TextAntialiasing);
        graphicActivity->setCacheMode(QGraphicsView::CacheNone);
        graphicTextPlacer = new QGraphicsView(widget);
        graphicTextPlacer->setObjectName(QString::fromUtf8("graphicTextPlacer"));
        graphicTextPlacer->setGeometry(QRect(162, 265, 328, 181));
        graphicTextPlacer->setFont(font);
        graphicTextPlacer->setStyleSheet(QString::fromUtf8("border:none;background-color: rgba(26, 26,26, 0);"));
        graphicTextPlacer->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicTextPlacer->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicTextPlacer->setRenderHints(QPainter::HighQualityAntialiasing);
        graphicTextPlacer->setCacheMode(QGraphicsView::CacheNone);
        VoiceScanBut = new QPushButton(widget);
        VoiceScanBut->setObjectName(QString::fromUtf8("VoiceScanBut"));
        VoiceScanBut->setGeometry(QRect(342, 253, 60, 10));
        VoiceScanBut->setFont(font);
        VoiceScanBut->setStyleSheet(QString::fromUtf8("color: rgb(130, 130, 130);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(130, 130, 130, 80);"));
        graphicsVoice = new QGraphicsView(widget);
        graphicsVoice->setObjectName(QString::fromUtf8("graphicsVoice"));
        graphicsVoice->setGeometry(QRect(220, 265, 270, 100));
        graphicsVoice->setFont(font);
        graphicsVoice->setStyleSheet(QString::fromUtf8("border:1px white solid;background-color: rgba(26, 26,26, 0);"));
        graphicsVoice->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsVoice->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsVoice->setRenderHints(QPainter::TextAntialiasing);
        graphicsVoice->setCacheMode(QGraphicsView::CacheNone);
        clearLogBut = new QPushButton(widget);
        clearLogBut->setObjectName(QString::fromUtf8("clearLogBut"));
        clearLogBut->setGeometry(QRect(475, 445, 16, 21));
        clearLogBut->setFont(font);
        clearLogBut->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(255, 255, 255, 40);"));
        secretMessageBut_1 = new QPushButton(widget);
        secretMessageBut_1->setObjectName(QString::fromUtf8("secretMessageBut_1"));
        secretMessageBut_1->setGeometry(QRect(415, 0, 5, 8));
        secretMessageBut_1->setFont(font);
        secretMessageBut_1->setStyleSheet(QString::fromUtf8("border: 0.5px solid #313131; background-color:qlineargradient(spread:pad, x1:0.511, y1:0.477727, x2:0.512, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.0113636 rgba(83, 83, 83, 255), stop:0.0568182 rgba(98, 98, 98, 255), stop:0.0625 rgba(167, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))"));
        secretMessageBut_2 = new QPushButton(widget);
        secretMessageBut_2->setObjectName(QString::fromUtf8("secretMessageBut_2"));
        secretMessageBut_2->setGeometry(QRect(420, 0, 5, 8));
        secretMessageBut_2->setFont(font);
        secretMessageBut_2->setStyleSheet(QString::fromUtf8("border: 0.5px solid #313131; background-color:qlineargradient(spread:pad, x1:0.511, y1:0.477727, x2:0.512, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.0113636 rgba(83, 83, 83, 255), stop:0.0568182 rgba(98, 98, 98, 255), stop:0.0625 rgba(167, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))"));
        secretMessageBut_3 = new QPushButton(widget);
        secretMessageBut_3->setObjectName(QString::fromUtf8("secretMessageBut_3"));
        secretMessageBut_3->setGeometry(QRect(425, 0, 5, 8));
        secretMessageBut_3->setFont(font);
        secretMessageBut_3->setStyleSheet(QString::fromUtf8("border: 0.5px solid #313131; background-color:qlineargradient(spread:pad, x1:0.511, y1:0.477727, x2:0.512, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.0113636 rgba(83, 83, 83, 255), stop:0.0568182 rgba(98, 98, 98, 255), stop:0.0625 rgba(167, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))"));
        secretMessageBut_4 = new QPushButton(widget);
        secretMessageBut_4->setObjectName(QString::fromUtf8("secretMessageBut_4"));
        secretMessageBut_4->setGeometry(QRect(430, 0, 5, 8));
        secretMessageBut_4->setFont(font);
        secretMessageBut_4->setStyleSheet(QString::fromUtf8("border: 0.5px solid #313131; background-color:qlineargradient(spread:pad, x1:0.511, y1:0.477727, x2:0.512, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.0113636 rgba(83, 83, 83, 255), stop:0.0568182 rgba(98, 98, 98, 255), stop:0.0625 rgba(167, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))"));
        secretMessageBut_5 = new QPushButton(widget);
        secretMessageBut_5->setObjectName(QString::fromUtf8("secretMessageBut_5"));
        secretMessageBut_5->setGeometry(QRect(435, 0, 5, 8));
        secretMessageBut_5->setFont(font);
        secretMessageBut_5->setStyleSheet(QString::fromUtf8("border: 0.5px solid #313131; background-color:qlineargradient(spread:pad, x1:0.511, y1:0.477727, x2:0.512, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.0113636 rgba(83, 83, 83, 255), stop:0.0568182 rgba(98, 98, 98, 255), stop:0.0625 rgba(167, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))"));
        secretMessageBut_6 = new QPushButton(widget);
        secretMessageBut_6->setObjectName(QString::fromUtf8("secretMessageBut_6"));
        secretMessageBut_6->setGeometry(QRect(440, 0, 5, 8));
        secretMessageBut_6->setFont(font);
        secretMessageBut_6->setStyleSheet(QString::fromUtf8("border: 0.5px solid #313131; background-color:qlineargradient(spread:pad, x1:0.511, y1:0.477727, x2:0.512, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.0113636 rgba(83, 83, 83, 255), stop:0.0568182 rgba(98, 98, 98, 255), stop:0.0625 rgba(167, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))"));
        secretMessageBut_7 = new QPushButton(widget);
        secretMessageBut_7->setObjectName(QString::fromUtf8("secretMessageBut_7"));
        secretMessageBut_7->setGeometry(QRect(445, 0, 5, 8));
        secretMessageBut_7->setFont(font);
        secretMessageBut_7->setStyleSheet(QString::fromUtf8("border: 0.5px solid #313131; background-color:qlineargradient(spread:pad, x1:0.511, y1:0.477727, x2:0.512, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.0113636 rgba(83, 83, 83, 255), stop:0.0568182 rgba(98, 98, 98, 255), stop:0.0625 rgba(167, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))"));
        secretMessageBut_8 = new QPushButton(widget);
        secretMessageBut_8->setObjectName(QString::fromUtf8("secretMessageBut_8"));
        secretMessageBut_8->setGeometry(QRect(450, 0, 5, 8));
        secretMessageBut_8->setFont(font);
        secretMessageBut_8->setStyleSheet(QString::fromUtf8("border: 0.5px solid #313131; background-color:qlineargradient(spread:pad, x1:0.511, y1:0.477727, x2:0.512, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.0113636 rgba(83, 83, 83, 255), stop:0.0568182 rgba(98, 98, 98, 255), stop:0.0625 rgba(167, 0, 0, 255), stop:1 rgba(255, 0, 0, 255))"));
        newMessageLabel = new QLabel(widget);
        newMessageLabel->setObjectName(QString::fromUtf8("newMessageLabel"));
        newMessageLabel->setGeometry(QRect(265, 53, 70, 10));
        sizePolicy.setHeightForWidth(newMessageLabel->sizePolicy().hasHeightForWidth());
        newMessageLabel->setSizePolicy(sizePolicy);
        newMessageLabel->setMinimumSize(QSize(0, 0));
        newMessageLabel->setFont(font);
        newMessageLabel->setStyleSheet(QString::fromUtf8("color:rgb(255, 0, 0);background-color: rgba(2, 2, 2, 0);"));
        newMessageLabel->setLineWidth(1);
        newMessageLabel->setWordWrap(false);
        PieStatBut = new QPushButton(widget);
        PieStatBut->setObjectName(QString::fromUtf8("PieStatBut"));
        PieStatBut->setGeometry(QRect(403, 253, 60, 10));
        PieStatBut->setFont(font);
        PieStatBut->setStyleSheet(QString::fromUtf8("color: rgb(130, 130, 130);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(130, 130, 130, 80);"));
        trayButton = new QPushButton(widget);
        trayButton->setObjectName(QString::fromUtf8("trayButton"));
        trayButton->setGeometry(QRect(455, 10, 10, 20));
        trayButton->setFont(font);
        trayButton->setStyleSheet(QString::fromUtf8("background-color: rgba(0, 0, 0, 0);"));
        DredLabel = new QLabel(widget);
        DredLabel->setObjectName(QString::fromUtf8("DredLabel"));
        DredLabel->setGeometry(QRect(235, 417, 8, 5));
        DredLabel->setFont(font);
        DredLabel->setStyleSheet(QString::fromUtf8("background-color: rgb(85, 0, 0);"));
        labelSSH = new QLabel(widget);
        labelSSH->setObjectName(QString::fromUtf8("labelSSH"));
        labelSSH->setGeometry(QRect(250, 415, 61, 8));
        labelSSH->setFont(font1);
        labelSSH->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        rVerLabel = new QLabel(widget);
        rVerLabel->setObjectName(QString::fromUtf8("rVerLabel"));
        rVerLabel->setEnabled(true);
        rVerLabel->setGeometry(QRect(31, 16, 82, 10));
        sizePolicy.setHeightForWidth(rVerLabel->sizePolicy().hasHeightForWidth());
        rVerLabel->setSizePolicy(sizePolicy);
        rVerLabel->setMinimumSize(QSize(0, 0));
        rVerLabel->setFont(font);
        rVerLabel->setStyleSheet(QString::fromUtf8("color:rgb(255, 0, 0);background-color: rgba(2, 2, 2, 0);"));
        rVerLabel->setLineWidth(1);
        rVerLabel->setWordWrap(false);
        NSTrackStatusLabel = new QLabel(widget);
        NSTrackStatusLabel->setObjectName(QString::fromUtf8("NSTrackStatusLabel"));
        NSTrackStatusLabel->setEnabled(true);
        NSTrackStatusLabel->setGeometry(QRect(456, 0, 8, 8));
        NSTrackStatusLabel->setFont(font);
        NSTrackStatusLabel->setStyleSheet(QString::fromUtf8("background-color: black; border: 1px solid #313131;"));
        graphicsTest = new QGraphicsView(widget);
        graphicsTest->setObjectName(QString::fromUtf8("graphicsTest"));
        graphicsTest->setGeometry(QRect(9, 229, 210, 211));
        graphicsTest->setFont(font);
        graphicsTest->setStyleSheet(QString::fromUtf8("border:1px white solid;background-color: rgba(26, 26,26, 0);"));
        graphicsTest->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsTest->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        graphicsTest->setRenderHints(QPainter::TextAntialiasing);
        graphicsTest->setCacheMode(QGraphicsView::CacheNone);
        labelSavedValue = new QLabel(widget);
        labelSavedValue->setObjectName(QString::fromUtf8("labelSavedValue"));
        labelSavedValue->setGeometry(QRect(105, 311, 67, 20));
        labelSavedValue->setFont(font7);
        labelSavedValue->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216); background-color: rgba(2, 2, 2, 0);"));
        labelSaved = new QLabel(widget);
        labelSaved->setObjectName(QString::fromUtf8("labelSaved"));
        labelSaved->setGeometry(QRect(88, 312, 16, 15));
        QFont font9;
        font9.setFamily(QString::fromUtf8("MS Sans Serif"));
        font9.setPointSize(8);
        font9.setBold(false);
        font9.setUnderline(false);
        font9.setWeight(50);
        font9.setKerning(false);
        labelSaved->setFont(font9);
        labelSaved->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        currentDirectoryLine = new QLineEdit(widget);
        currentDirectoryLine->setObjectName(QString::fromUtf8("currentDirectoryLine"));
        currentDirectoryLine->setGeometry(QRect(20, 780, 351, 16));
        QFont font10;
        font10.setPointSize(7);
        currentDirectoryLine->setFont(font10);
        currentDirectoryLine->setMouseTracking(false);
        currentDirectoryLine->setFocusPolicy(Qt::NoFocus);
        currentDirectoryLine->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);"));
        currentDirectoryLine->setFrame(false);
        currentDirectoryLine->setReadOnly(true);
        BATableView = new QTableView(widget);
        BATableView->setObjectName(QString::fromUtf8("BATableView"));
        BATableView->setGeometry(QRect(20, 445, 453, 326));
        BATableView->setFont(font);
        BATableView->setStyleSheet(QString::fromUtf8("background-color: rgb(26, 26,26); border: 1px solid white;"));
        BATableView->setLocale(QLocale(QLocale::English, QLocale::UnitedStates));
        BATableView->setFrameShape(QFrame::NoFrame);
        BATableView->setFrameShadow(QFrame::Plain);
        BATableView->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        BATableView->setSelectionMode(QAbstractItemView::SingleSelection);
        BATableView->setSelectionBehavior(QAbstractItemView::SelectRows);
        BATableView->setCornerButtonEnabled(false);
        BATableView->horizontalHeader()->setVisible(false);
        BATableView->verticalHeader()->setVisible(false);
        BATableView->verticalHeader()->setMinimumSectionSize(10);
        BATableView->verticalHeader()->setDefaultSectionSize(20);
        BATableView->raise();
        graphicTextPlacer->raise();
        labelNesca_3->raise();
        tabMainWidget->raise();
        line->raise();
        exitButton->raise();
        dataText->raise();
        line_2->raise();
        RedLabel->raise();
        YellowLabel->raise();
        GreenLabel->raise();
        BlueLabel->raise();
        CyanLabel->raise();
        PinkLabel->raise();
        labelAnomaly->raise();
        labelBA->raise();
        labelFiltered->raise();
        labelBads->raise();
        labelOverloads->raise();
        labelLowloads->raise();
        graphicLog->raise();
        logoLabel->raise();
        WhiteLabel->raise();
        labelAlives->raise();
        me2ScanBut->raise();
        QoSScanBut->raise();
        graphicDelim->raise();
        graphicLog_2->raise();
        graphicLog_Upper->raise();
        switcherBut->raise();
        graphicActivityGrid->raise();
        graphicActivity->raise();
        VoiceScanBut->raise();
        graphicsVoice->raise();
        clearLogBut->raise();
        secretMessageBut_1->raise();
        secretMessageBut_2->raise();
        secretMessageBut_3->raise();
        secretMessageBut_4->raise();
        secretMessageBut_5->raise();
        secretMessageBut_6->raise();
        secretMessageBut_7->raise();
        secretMessageBut_8->raise();
        newMessageLabel->raise();
        PieStatBut->raise();
        trayButton->raise();
        DredLabel->raise();
        labelSSH->raise();
        rVerLabel->raise();
        NSTrackStatusLabel->raise();
        graphicsTest->raise();
        ipLabel->raise();
        labelTargetsLeft->raise();
        labelPendingTargets->raise();
        labelThreads->raise();
        labelRunningThreads->raise();
        labelSavedValue->raise();
        labelSaved->raise();
        currentDirectoryLine->raise();
        widgetJOB = new QWidget(centralWidget);
        widgetJOB->setObjectName(QString::fromUtf8("widgetJOB"));
        widgetJOB->setGeometry(QRect(500, 44, 498, 730));
        widgetJOB->setFont(font);
        widgetJOB->setStyleSheet(QString::fromUtf8("background-color:qlineargradient(spread:pad, x1:0.541, y1:0.500364, x2:0.54, y2:0, stop:0 rgba(16, 16, 16, 255), stop:1 rgba(0, 0, 0, 255));"));
        jobRangeVisual = new QGraphicsView(widgetJOB);
        jobRangeVisual->setObjectName(QString::fromUtf8("jobRangeVisual"));
        jobRangeVisual->setGeometry(QRect(10, 30, 480, 41));
        jobRangeVisual->setFont(font);
        jobRangeVisual->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        jobRangeVisual->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        jobIPContractsTable = new QTableWidget(widgetJOB);
        jobIPContractsTable->setObjectName(QString::fromUtf8("jobIPContractsTable"));
        jobIPContractsTable->setGeometry(QRect(10, 105, 480, 296));
        jobIPContractsTable->setFont(font);
        jobIPWantedTable = new QTableWidget(widgetJOB);
        jobIPWantedTable->setObjectName(QString::fromUtf8("jobIPWantedTable"));
        jobIPWantedTable->setGeometry(QRect(10, 425, 480, 296));
        jobIPWantedTable->setFont(font);
        DataflowModeBut = new QPushButton(centralWidget);
        DataflowModeBut->setObjectName(QString::fromUtf8("DataflowModeBut"));
        DataflowModeBut->setGeometry(QRect(440, 50, 48, 16));
        DataflowModeBut->setFont(font);
        DataflowModeBut->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(255, 255, 255, 40);"));
        JobModeBut = new QPushButton(centralWidget);
        JobModeBut->setObjectName(QString::fromUtf8("JobModeBut"));
        JobModeBut->setGeometry(QRect(390, 50, 48, 16));
        JobModeBut->setFont(font);
        JobModeBut->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(255, 255, 255, 40);"));
        edit_filter_button = new QPushButton(centralWidget);
        edit_filter_button->setObjectName(QString::fromUtf8("edit_filter_button"));
        edit_filter_button->setGeometry(QRect(340, 50, 48, 16));
        edit_filter_button->setFont(font);
        edit_filter_button->setStyleSheet(QString::fromUtf8("color: rgb(216, 216, 216);background-color: rgba(2, 2, 2, 0);border: 1px solid rgba(255, 255, 255, 40);"));
        nesca_3Class->setCentralWidget(centralWidget);
        widgetJOB->raise();
        widget->raise();
        DataflowModeBut->raise();
        JobModeBut->raise();
        edit_filter_button->raise();
        QWidget::setTabOrder(ipLine, ipmPortLine);
        QWidget::setTabOrder(ipmPortLine, threadLine);
        QWidget::setTabOrder(threadLine, dnsLine);
        QWidget::setTabOrder(dnsLine, lineILVL);
        QWidget::setTabOrder(lineILVL, dnsPortLine);
        QWidget::setTabOrder(dnsPortLine, lineEditThread);
        QWidget::setTabOrder(lineEditThread, lineTrackerSrv);
        QWidget::setTabOrder(lineTrackerSrv, lineTrackerScr);
        QWidget::setTabOrder(lineTrackerScr, linePersKey);
        QWidget::setTabOrder(linePersKey, trackerOnOff);
        QWidget::setTabOrder(trackerOnOff, tabMainWidget);
        QWidget::setTabOrder(tabMainWidget, startScanButton_3);
        QWidget::setTabOrder(startScanButton_3, startScanButton_4);
        QWidget::setTabOrder(startScanButton_4, exitButton);
        QWidget::setTabOrder(exitButton, dataText);

        retranslateUi(nesca_3Class);

        tabMainWidget->setCurrentIndex(3);


        QMetaObject::connectSlotsByName(nesca_3Class);
    } // setupUi

    void retranslateUi(QMainWindow *nesca_3Class)
    {
        nesca_3Class->setWindowTitle(QCoreApplication::translate("nesca_3Class", "NESCA 3", nullptr));
        startScanButton_3->setText(QCoreApplication::translate("nesca_3Class", "Start", nullptr));
        ipLine->setText(QCoreApplication::translate("nesca_3Class", "1.1.1.1-255.255.255.255", nullptr));
        ipLine->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "000.000.000.000-255.255.255.255", nullptr));
        ipmPortLine->setText(QCoreApplication::translate("nesca_3Class", "80,81,88,8080,8081,60001,60002,8008,8888,554,9000,3536,21", nullptr));
        ipmPortLine->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "80,81,8080,8888,21,6667,7000", nullptr));
        threadLine->setText(QCoreApplication::translate("nesca_3Class", "200", nullptr));
        threadLine->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "100", nullptr));
        labelIPRange->setText(QCoreApplication::translate("nesca_3Class", "IP RANGE", nullptr));
        labelIPPorts->setText(QCoreApplication::translate("nesca_3Class", "PORTS", nullptr));
        labelIPThreads->setText(QCoreApplication::translate("nesca_3Class", "THREADS", nullptr));
        labelIPTO->setText(QCoreApplication::translate("nesca_3Class", "TIMEOUT", nullptr));
        iptoLine_value->setText(QCoreApplication::translate("nesca_3Class", "3", nullptr));
        iptoLine_value->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "100", nullptr));
#if QT_CONFIG(tooltip)
        restoreDefaultPorts1->setToolTip(QCoreApplication::translate("nesca_3Class", "Restore default ports", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        restoreDefaultPorts1->setWhatsThis(QCoreApplication::translate("nesca_3Class", "Restore default ports", nullptr));
#endif // QT_CONFIG(whatsthis)
        restoreDefaultPorts1->setText(QCoreApplication::translate("nesca_3Class", ":Default ports", nullptr));
        tabMainWidget->setTabText(tabMainWidget->indexOf(tab_4), QCoreApplication::translate("nesca_3Class", "IP Scan", nullptr));
        dnsLine->setText(QCoreApplication::translate("nesca_3Class", "[09][az][0-]", nullptr));
        dnsLine->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "[09][az][0-][09][az][0-]", nullptr));
        startScanButton_4->setText(QCoreApplication::translate("nesca_3Class", "Start", nullptr));
        lineILVL->setText(QCoreApplication::translate("nesca_3Class", ".mobi", nullptr));
        lineILVL->setPlaceholderText(QCoreApplication::translate("nesca_3Class", ".mobi", nullptr));
        dnsPortLine->setText(QCoreApplication::translate("nesca_3Class", "80,81,88,8080,8081,60001,60002,8008,8888,554,9000,3536,21", nullptr));
        dnsPortLine->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "80,81,8080,8888,21,6667,7000", nullptr));
        lineEditThread->setText(QCoreApplication::translate("nesca_3Class", "30", nullptr));
        lineEditThread->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "100", nullptr));
        labelDNSRange->setText(QCoreApplication::translate("nesca_3Class", "DNS RANGE", nullptr));
        labelDNSPorts->setText(QCoreApplication::translate("nesca_3Class", "PORTS", nullptr));
        labelDNSThreads->setText(QCoreApplication::translate("nesca_3Class", "THREADS", nullptr));
        labelIPTO_2->setText(QCoreApplication::translate("nesca_3Class", "TIMEOUT", nullptr));
        iptoLine_value_2->setText(QCoreApplication::translate("nesca_3Class", "2", nullptr));
        iptoLine_value_2->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "100", nullptr));
#if QT_CONFIG(tooltip)
        restoreDefaultPorts2->setToolTip(QCoreApplication::translate("nesca_3Class", "Restore default ports", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        restoreDefaultPorts2->setWhatsThis(QCoreApplication::translate("nesca_3Class", "Restore default ports", nullptr));
#endif // QT_CONFIG(whatsthis)
        restoreDefaultPorts2->setText(QCoreApplication::translate("nesca_3Class", ":Default ports", nullptr));
        tabMainWidget->setTabText(tabMainWidget->indexOf(tab_5), QCoreApplication::translate("nesca_3Class", "DNS Scan", nullptr));
        importButton->setText(QCoreApplication::translate("nesca_3Class", "Import&&Scan", nullptr));
        labelIpRange_9->setText(QCoreApplication::translate("nesca_3Class", "Please, read about the import file in do_not_read.txt.", nullptr));
        importThreads->setText(QCoreApplication::translate("nesca_3Class", "200", nullptr));
        importThreads->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "100", nullptr));
        importPortLine->setText(QCoreApplication::translate("nesca_3Class", "80,81,88,8080,8081,60001,60002,8008,8888,554,9000,3536,21", nullptr));
        importPortLine->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "80,81,8080,8888,21,6667,7000", nullptr));
        labelDNSThreads_2->setText(QCoreApplication::translate("nesca_3Class", "THREADS", nullptr));
        labelDNSPorts_2->setText(QCoreApplication::translate("nesca_3Class", "PORTS", nullptr));
        labelIPTO_3->setText(QCoreApplication::translate("nesca_3Class", "TIMEOUT", nullptr));
        iptoLine_value_3->setText(QCoreApplication::translate("nesca_3Class", "3", nullptr));
        iptoLine_value_3->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "100", nullptr));
#if QT_CONFIG(tooltip)
        restoreDefaultPorts3->setToolTip(QCoreApplication::translate("nesca_3Class", "Restore default ports", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        restoreDefaultPorts3->setWhatsThis(QCoreApplication::translate("nesca_3Class", "Restore default ports", nullptr));
#endif // QT_CONFIG(whatsthis)
        restoreDefaultPorts3->setText(QCoreApplication::translate("nesca_3Class", ":Default ports", nullptr));
        tabMainWidget->setTabText(tabMainWidget->indexOf(tab_6), QCoreApplication::translate("nesca_3Class", "Import", nullptr));
#if QT_CONFIG(whatsthis)
        trackerOnOff->setWhatsThis(QCoreApplication::translate("nesca_3Class", "d3w.org database (NDB) collects all found sites for structuring and further analysis.", nullptr));
#endif // QT_CONFIG(whatsthis)
        trackerOnOff->setText(QCoreApplication::translate("nesca_3Class", "Send results to public NescaDatabase", nullptr));
        lineTrackerScr->setText(QCoreApplication::translate("nesca_3Class", "/go/", nullptr));
        lineTrackerScr->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "Balancer script", nullptr));
        lineTrackerSrv->setText(QCoreApplication::translate("nesca_3Class", "balancer.d3w.org", nullptr));
        lineTrackerSrv->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "Balancer url", nullptr));
        linePersKey->setText(QString());
        linePersKey->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "Your personal key here", nullptr));
        trcSrvPortLine->setText(QCoreApplication::translate("nesca_3Class", "80", nullptr));
        trcSrvPortLine->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "Balancer port here", nullptr));
        checkKeyBut->setText(QCoreApplication::translate("nesca_3Class", "Check key", nullptr));
#if QT_CONFIG(whatsthis)
        pingingOnOff->setWhatsThis(QCoreApplication::translate("nesca_3Class", "Ping hosts before connection attempts.", nullptr));
#endif // QT_CONFIG(whatsthis)
        pingingOnOff->setText(QCoreApplication::translate("nesca_3Class", "Ping hosts", nullptr));
#if QT_CONFIG(shortcut)
        pingingOnOff->setShortcut(QCoreApplication::translate("nesca_3Class", "Ctrl+S", nullptr));
#endif // QT_CONFIG(shortcut)
        PingTO->setText(QCoreApplication::translate("nesca_3Class", "2", nullptr));
        PingTO->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "100", nullptr));
        label->setText(QCoreApplication::translate("nesca_3Class", "sec", nullptr));
        threadDelayBox->setText(QCoreApplication::translate("nesca_3Class", "10", nullptr));
        threadDelayBox->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "100", nullptr));
        label_2->setText(QCoreApplication::translate("nesca_3Class", "Thread delay:", nullptr));
        MaxBrutingThrLabel->setText(QCoreApplication::translate("nesca_3Class", "Max bruting\n"
" threads:", nullptr));
        maxBrutingThrBox->setText(QCoreApplication::translate("nesca_3Class", "2000", nullptr));
        maxBrutingThrBox->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "2000", nullptr));
#if QT_CONFIG(whatsthis)
        shuffle_onoff->setWhatsThis(QCoreApplication::translate("nesca_3Class", "Shuffle ip-ranges before scan.", nullptr));
#endif // QT_CONFIG(whatsthis)
        shuffle_onoff->setText(QCoreApplication::translate("nesca_3Class", "Shuffle ip ranges", nullptr));
#if QT_CONFIG(shortcut)
        shuffle_onoff->setShortcut(QCoreApplication::translate("nesca_3Class", "Ctrl+S", nullptr));
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        systemProxyIP->setToolTip(QString());
#endif // QT_CONFIG(tooltip)
        systemProxyIP->setText(QString());
        systemProxyIP->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "Proxy here", nullptr));
        systemProxyPort->setText(QCoreApplication::translate("nesca_3Class", "3128", nullptr));
        systemProxyPort->setPlaceholderText(QCoreApplication::translate("nesca_3Class", "Balancer port here", nullptr));
        tabMainWidget->setTabText(tabMainWidget->indexOf(tab), QCoreApplication::translate("nesca_3Class", "Options", nullptr));
        labelNesca_3->setText(QCoreApplication::translate("nesca_3Class", "NESCA 3 :: Revealing the Unseen Horizon", nullptr));
        exitButton->setText(QCoreApplication::translate("nesca_3Class", "X", nullptr));
        labelThreads->setText(QCoreApplication::translate("nesca_3Class", "\342\207\211:", nullptr));
        ipLabel->setText(QCoreApplication::translate("nesca_3Class", "--", nullptr));
        labelRunningThreads->setText(QCoreApplication::translate("nesca_3Class", "0/0/0", nullptr));
        dataText->setHtml(QCoreApplication::translate("nesca_3Class", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Small Fonts'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Verdana'; font-size:6pt;\"><br /></p></body></html>", nullptr));
        labelTargetsLeft->setText(QCoreApplication::translate("nesca_3Class", "\342\214\276:", nullptr));
        labelPendingTargets->setText(QCoreApplication::translate("nesca_3Class", "0", nullptr));
        RedLabel->setText(QString());
        YellowLabel->setText(QString());
        GreenLabel->setText(QString());
        BlueLabel->setText(QString());
        CyanLabel->setText(QString());
        PinkLabel->setText(QString());
        labelAnomaly->setText(QCoreApplication::translate("nesca_3Class", "Cameras", nullptr));
        labelBA->setText(QCoreApplication::translate("nesca_3Class", "Basic Auth", nullptr));
        labelFiltered->setText(QCoreApplication::translate("nesca_3Class", "Other", nullptr));
        labelBads->setText(QCoreApplication::translate("nesca_3Class", "--", nullptr));
        labelOverloads->setText(QCoreApplication::translate("nesca_3Class", "Overloads", nullptr));
        labelLowloads->setText(QCoreApplication::translate("nesca_3Class", "--", nullptr));
        logoLabel->setText(QString());
        WhiteLabel->setText(QString());
        labelAlives->setText(QCoreApplication::translate("nesca_3Class", "Alive", nullptr));
        me2ScanBut->setText(QCoreApplication::translate("nesca_3Class", ":ME2 mode", nullptr));
        QoSScanBut->setText(QCoreApplication::translate("nesca_3Class", ":QoS  mode", nullptr));
#if QT_CONFIG(tooltip)
        switcherBut->setToolTip(QCoreApplication::translate("nesca_3Class", "Brute activity", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        switcherBut->setWhatsThis(QCoreApplication::translate("nesca_3Class", "Brute activity", nullptr));
#endif // QT_CONFIG(whatsthis)
        switcherBut->setText(QCoreApplication::translate("nesca_3Class", "<", nullptr));
        VoiceScanBut->setText(QCoreApplication::translate("nesca_3Class", ":Voice mode", nullptr));
#if QT_CONFIG(tooltip)
        clearLogBut->setToolTip(QCoreApplication::translate("nesca_3Class", "Clear logs", "Clear log"));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        clearLogBut->setWhatsThis(QCoreApplication::translate("nesca_3Class", "Clear logs", nullptr));
#endif // QT_CONFIG(whatsthis)
        clearLogBut->setText(QCoreApplication::translate("nesca_3Class", "X", nullptr));
        secretMessageBut_1->setText(QString());
        secretMessageBut_2->setText(QString());
        secretMessageBut_3->setText(QString());
        secretMessageBut_4->setText(QString());
        secretMessageBut_5->setText(QString());
        secretMessageBut_6->setText(QString());
        secretMessageBut_7->setText(QString());
        secretMessageBut_8->setText(QString());
        newMessageLabel->setText(QCoreApplication::translate("nesca_3Class", "New message", nullptr));
        PieStatBut->setText(QCoreApplication::translate("nesca_3Class", ":Pie statistics", nullptr));
        trayButton->setText(QCoreApplication::translate("nesca_3Class", "_", nullptr));
        DredLabel->setText(QString());
        labelSSH->setText(QCoreApplication::translate("nesca_3Class", "SSH", nullptr));
        rVerLabel->setText(QCoreApplication::translate("nesca_3Class", "Outdated version", nullptr));
        NSTrackStatusLabel->setText(QString());
        labelSavedValue->setText(QCoreApplication::translate("nesca_3Class", "0", nullptr));
        labelSaved->setText(QCoreApplication::translate("nesca_3Class", "\342\234\224:", nullptr));
        currentDirectoryLine->setText(QString());
#if QT_CONFIG(tooltip)
        DataflowModeBut->setToolTip(QCoreApplication::translate("nesca_3Class", "Online datastream", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        DataflowModeBut->setWhatsThis(QCoreApplication::translate("nesca_3Class", "Online datastream", nullptr));
#endif // QT_CONFIG(whatsthis)
        DataflowModeBut->setText(QCoreApplication::translate("nesca_3Class", ":Dataflow", nullptr));
#if QT_CONFIG(tooltip)
        JobModeBut->setToolTip(QCoreApplication::translate("nesca_3Class", "IP range distribution", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        JobModeBut->setWhatsThis(QCoreApplication::translate("nesca_3Class", "IP range distribution", nullptr));
#endif // QT_CONFIG(whatsthis)
        JobModeBut->setText(QCoreApplication::translate("nesca_3Class", ":Jobs", nullptr));
#if QT_CONFIG(tooltip)
        edit_filter_button->setToolTip(QCoreApplication::translate("nesca_3Class", "Edit negatives.txt", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        edit_filter_button->setWhatsThis(QCoreApplication::translate("nesca_3Class", "IP range distribution", nullptr));
#endif // QT_CONFIG(whatsthis)
        edit_filter_button->setText(QCoreApplication::translate("nesca_3Class", ":Edit filter", nullptr));
    } // retranslateUi

};

namespace Ui {
    class nesca_3Class: public Ui_nesca_3Class {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_NESCA_3_H
